version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: mypostgresdb
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: Secret12345!
      POSTGRES_DB: mydatabase
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - mypostgresdb_data:/var/lib/postgresql/data
    networks:
      - mynetwork
    restart: always

  webapi:
    image: mywebapi
    build:
      context: .
      dockerfile: app.Dockerfile
    container_name: mywebapiapp
    environment:
      ASPNETCORE_URLS: http://+:80
    depends_on:
      - postgres
    ports:
      - 5000:80
    networks:
      - mynetwork
    restart: always

networks:
  mynetwork:
    driver: bridge

volumes:
  mypostgresdb_data: